src/Entity/Offert.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass="App\Repository\OffertRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Offert
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string",length=50)
     */
    private $employer_id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank(message="To pole nie może być puste")
     *    @Assert\Length(
     *      max = 50,
     *      maxMessage = "Wyraz nie może być dłuższy niż {{ limit }} znaków"
     * )
     */
    private $title;

    /**
     * @Assert\NotBlank(message="To pole nie może być puste")
     *        @Assert\Length(
     *      max = 10000,
     *      maxMessage = "Wyraz nie może być dłuższy niż {{ limit }} znaków"
     * )
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $addedAt;
    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    private $editedAt;

    /**
     * @Assert\NotBlank(message="To pole nie może być puste")
     * @ORM\Column(type="integer", nullable=true)
     */
    private $salaryMin;

    /**
     * @Assert\NotBlank(message="To pole nie może być puste")
     * @ORM\Column(type="integer", nullable=true)
     */
    private $salaryMax;



    /**
     * @Assert\NotBlank(message="To pole nie może być puste")
     * @ORM\Column(type="string", length=100)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Skill", mappedBy="offert",orphanRemoval=true ,cascade={"persist"})
     */
    private $skill;

    public function __construct()
    {
        $this->skill = new ArrayCollection();
        $this->addedAt = new \DateTime();
    }

   
    public function prePersist()
    {
        $this->editedAt = new \DateTime();
    }
    public function getId(): ?int
    {
        return $this->id;
    }


    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getEmployerId()
    {
        return $this->employer_id;
    }

    /**
     * @param mixed $employer_id
     */
    public function setEmployerId($employer_id): void
    {
        $this->employer_id = $employer_id;
    }

    public function getAddedAt(): ?\DateTimeInterface
    {
        return $this->addedAt;
    }

    public function setAddedAt(\DateTimeInterface $addedAt): self
    {
        $this->addedAt = $addedAt;

        return $this;
    }
    public function getEditedAt(): ?\DateTimeInterface
    {
        return $this->editedAt;
    }

    public function setEditedAt(\DateTimeInterface $editedAt): self
    {
        $this->addedAt = $editedAt;

        return $this;
    }

    public function getSalaryMin(): ?int
    {
        return $this->salaryMin;
    }

    public function setSalaryMin(?int $salaryMin): self
    {
        $this->salaryMin = $salaryMin;

        return $this;
    }

    public function getSalaryMax(): ?int
    {
        return $this->salaryMax;
    }

    public function setSalaryMax(?int $salaryMax): self
    {
        $this->salaryMax = $salaryMax;

        return $this;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Skill[]
     */
    public function getSkill(): Collection
    {
        return $this->skill;
    }

    public function addSkill(Skill $skill): self
    {
        if (!$this->skill->contains($skill)) {
            $this->skill[] = $skill;
            $skill->setOffert($this);
        }

        return $this;
    }

    public function removeSkill(Skill $skill): self
    {
        if ($this->skill->contains($skill)) {
            $this->skill->removeElement($skill);
            // set the owning side to null (unless already changed)
            if ($skill->getOffert() === $this) {
                $skill->setOffert(null);
            }
        }

        return $this;
    }
}

src/Form/OffertType.php
<?php
/**
 * Created by PhpStorm.
 * User: Bartek1
 * Date: 2018-10-17
 * Time: 19:26
 */



namespace App\Form;







use App\Entity\Offert;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OffertType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',TextType::class,array('label' => false))
            ->add('description',TextType::class,array('label' => false))
            ->add('content',TextareaType::class,array('label' => false))
            ->add('salaryMin',IntegerType::class,array('label' => false))
            ->add('salaryMax',IntegerType::class,array('label' => false))
            ->add('skill', CollectionType::class, array(
            'entry_type' => SkillType::class,
            'label' => false,
            'entry_options' => array('label' => false),
                'allow_add' => true,
                'by_reference' => false,
                'allow_delete' => true,
                'prototype' => true,
                'attr' => array(
                    'class' => 'skills',
                ),
            ));

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Offert::class,
        ));
    }



}

src/Controller/OffertController.php
<?php

namespace App\Controller;



use App\Entity\Offert;
use App\Form\OffertType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class OffertController extends AbstractController
{
    /**
     * @Route("/home/e/offert/add", name="offert_add")
     */
    public function add(ValidatorInterface $validator,Request $request,EntityManagerInterface $em,UserInterface $user = null)
    {
        $username = $user->getUsername();
        $offert = new Offert();
        $offert->setEmployerId($username);
        $form = $this->createForm(OffertType::class,$offert);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $offert = $form->getData();
            $errors = $validator->validate($offert);
            if (count($errors) > 0) {
                $errorsString = (string) $errors;
                return new Response($errorsString);
            }
            $em->persist($offert);
            $em->flush();
        }
        return $this->render('offert/add.html.twig', [
            'form' => $form->createView()
        ]);
    }


    /**
     * @Route("/home/e/offert/edit/{id}", name="offert_edit")
     */
    public function edit(ValidatorInterface $validator,Request $request,EntityManagerInterface $em,string $id,UserInterface $user = null)
    {
        $offert = $em->getRepository(Offert::class)->find($id);
        $form = $this->createForm(OffertType::class, $offert);
        $username = $user->getUsername();
        $offert->setEmployerId($username);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $offert = $form->getData();
            $errors = $validator->validate($offert);
            if (count($errors) > 0) {
                $errorsString = (string) $errors;
                return new Response($errorsString);
            }
            $em->persist($offert);
            $em->flush();
        }
        return $this->render('offert/add.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/home/offert/show", name="offert_show_all")
     */
    public function show(EntityManagerInterface $em)
    {
        $repository = $em->getRepository(Offert::class);
        $offert = $repository->findAll();
        return $this->render('offert/all.html.twig', [
            "offerts" => $offert,

        ]);
    }

    /**
     * @Route("/home/offert/show/{id}", name="offert_show")
     */
    public function showOne(EntityManagerInterface $em,string $id)
    {

        $repository = $em->getRepository(Offert::class);
        $offert = $repository->find($id);

        return $this->render('offert/index.html.twig', [
            "offert" => $offert,
        ]);
    }

}

templates/offert/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }}{% endblock %}
{% block navtitle %}Dodawanie oferty{% endblock %}

{% block body %}
    <script src="https://cdn.ckeditor.com/4.11.1/basic/ckeditor.js"></script>
 {% form_theme form
     'offert-form-theme.html.twig'
     'jquery.collection.html.twig'  %}
    <div class="col-sm-12 col-md-12 center-block">
        <div class="card mb-12">
            <div class="card-block">
                <h3 class="card-title"></h3>
                <h6 class="card-subtitle mb-2 text-muted"></h6>

                {{ form_start(form,{'attr': {'novalidate':'true'}}) }}
                {{ form_errors(form) }}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Nazwa oferty</label>
                        {{ form_row(form.title) }}
                    </div>
                    <div class="form-group col-md-6">
                        <label>Stanowisko</label>
                        {{ form_row(form.description) }}
                    </div>
                </div>
                <div class="form-group">
                    <label>Opis</label>
                    {{ form_row(form.content) }}
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label >Wynagrodzenie minimalne</label>
                        {{ form_row(form.salaryMin) }}
                    </div>
                    <div class="form-group col-md-6">
                        <label>Wynagrodzenie maksymalne</label>
                        {{ form_row(form.salaryMax) }}
                    </div>
                </div>
                <div class="form-group">
                    <label >Umiejętności</label>
                    {{ form_row(form.skill) }}
                </div>
                <button type="submit" class="btn btn-primary">Zapisz</button>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
    {% block javascripts %}
        {{ parent() }}
        <script src="{{ asset('web/js/jquery.collection.js') }}"></script>
        <script>
            $('.skills').collection({
                allow_up: false,
                allow_down: false,
                prefix: 'skill',

            });
        </script>
        <script>
            CKEDITOR.replace( 'offert[content]' );
        </script>
    {% endblock %}
{% endblock %}

templates/offert/all.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ parent() }}{% endblock %}
{% block navtitle %}Oferty pracy{% endblock %}


{% block body %}

    <div class="card mb-4">
        <div class="card-block">
            <h3 class="card-title">Oferty pracy</h3>

            <div class="table-responsive">
                <table class="table table-striped" id="table_id">
                    <thead>
                    <tr>
                        <th>Data dodania</th>
                        <th>Nazwa</th>
                        <th>Firma</th>
                        <th>Pensja</th>
                    </tr>
                    </thead>
                    <tbody>
    {% for offert in offerts  %}
                    <tr>
                        <td>{{  offert.addedAt|date("d-m-Y")  }}</td>
                        <td><a href="{{ path('offert_show', {'id': offert.id}) }}">{{ offert.title }}</a></td>
                        <td>{{ offert.employerId }}</td>
                        <td>{{ offert.salaryMin }}PLN-{{ offert.salaryMax }}PLN</td>
                    </tr>
    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script>

        $(document).ready(function() {
            $.noConflict();
            $('#table_id').dataTable( {
                language: {
                    url: "//cdn.datatables.net/plug-ins/1.10.19/i18n/Polish.json"
                }
            } );
        } );


    </script>



{% endblock %}

templates/offert/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }}{% endblock %}
{% block navtitle %}{{ offert.title }}{% endblock %}

{% block body %}

    <div class="card-block">
        <h3 class="card-title purple">{{ offert.title |upper}}</h3>
        {% for message in app.flashes('message') %}
            <div class="alert bg-success" role="alert"><em class="fa fa-minus-circle mr-2"></em>
                {{ message }}
            </div>
        {% endfor %}
        {% for alert in app.flashes('alert') %}
            <div class="alert bg-danger" role="alert"><em class="fa fa-minus-circle mr-2"></em>
                {{ alert }}
            </div>
        {% endfor %}
        <h5 class="card-title">Stanowisko: {{ offert.description }}</h5>
        {% if(is_granted('ROLE_USER')) %}
            <a href={{ path('answer', {offertId : offert.id}) }}><button type="button" class="btn btn-default">ODPOWIEDZ</button></a>
        {% endif %}
        <h3 class="card-title purple">Opis stanowiska</h3>
        <div class="card mb-4">
            <div class="card-block btn-margins">
                <p>{{ offert.content|raw }}</p>
            </div>
        </div>
        <h3 class="card-title purple">Płaca</h3>
        <div class="card mb-4">
            <div class="card-block btn-margins">
                <p>{{ offert.salaryMin }} PLN - {{ offert.salaryMax }} PLN</p>
            </div>
        </div>
        <h3 class="card-title purple">Wymagane umiejętności</h3>
        <section class="row">
            <div class="col-sm-12">

                <section class="row">
                    {% for skill in offert.skill %}
                    <div class="col-md-4 mb-2">
                        <div class="card mb-3 text-center ">
                            <div class="card-block">
                                <div class="easypiechart easypiechart-1"  data-percent="{{ skill.value }}" ></div>
                                <h5 class="mt-2 mb-1">{{ skill.name }}</h5>
                                <p class="mb-1">{{ skill.value }} %</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </section>

            </div>
        </section>
    </div>
     {% block javascripts %}
         {{ parent() }}
         <script src="{{ asset('web/js/easypiechart.js') }}"></script>
         <script src="{{ asset('web/js/easypiechart-data.js') }}"></script>
     {% endblock %}
{% endblock %}